# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap
  ps: Start-FileDownload 'https://ci.appveyor.com/api/buildjobs/cx4yar11hk7kspke/artifacts/data.table_1.10.5.zip'

cache:
  - C:\RLibrary
  

# Adapt as necessary starting from here

install:
  - ps: 


environment:
  matrix:
    - R_VERSION: devel
      R_ARCH: i386

build_script:
  - R -e 'install.packages("data.table_1.10.5.zip", repos = NULL, type = "win.binary")'
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

